In [67]:
import numpy as np
from sympy import *
def calcCn(N):
    n=symbols('n')
    f=sqrt(3)/pi*(sin((n-3)*pi/3)/(n-3)-sin((n+3)*pi/3)/(n+3))
    y=limit(f,n,N)
    return round(y,4)

def enStates(N):
    hbar=symbols('hbar')
    m=symbols('m')
    L=symbols('L')
    p=symbols('p')
    f=(N**2*p**2*hbar**2/(18*m*L)).evalf()
    return f
#1=calcCn(1)
print(calcCn(1))

print(calcCn(2))
print(calcCn(4))
print(calcCn(5))
print(calcCn(6))
print(enStates(3))

0.3581
0.5730
0.4093
0.1790
0
0.5*hbar**2*p**2/(L*m)


In [93]:
Ns=6
cn=np.zeros((Ns,1))
cEn=np.zeros((Ns,1))
En=[]
for n in range(Ns):
    
   cn[n]=calcCn(n+1)
   En.append(enStates(n))
   cEn[n]=(n+1)**2
   
print(cn)
print(cn**2)
print(sum(c**2))
print(cEn)

[[0.35810089]
 [0.57299805]
 [0.57740021]
 [0.40930176]
 [0.17900085]
 [0.        ]]
[[0.12823625]
 [0.32832676]
 [0.333391  ]
 [0.16752793]
 [0.03204131]
 [0.        ]]
0.9996
[[ 1.]
 [ 4.]
 [ 9.]
 [16.]
 [25.]
 [36.]]


In [95]:
print(sum(cEn*cn))

[18.87054443]


In [96]:
print(sum(cEn*cn))

[18.87054443]


In [82]:
%%latex
$
E\Psi(x)=\overline{\rm H}\Psi(x)   \\

for \ bound \ states\ ,  

E\Psi(x)=[-\frac{ \hbar^2}{2m} \frac{\partial^2 }{\partial x^2} -V_0]\Psi(x)   \\

-\frac{ 2mE}{\hbar^2}\Psi(x)=\frac{\partial^2 \Psi(x)}{\partial x^2}      \\

        
 N^2 3L=2  \\
 N=\sqrt{\frac{2}{3L}} \\
 
 \Psi(x)=\sqrt{\frac{2}{3L}}sin(\frac{n \pi x}{3L})=0   \\
 \frac{2mE}{\hbar^2} =\frac {n^2 \pi^2}{9L^2}  \\
 
 E= \frac {n^2 \pi^2\hbar^2}{18mL^2}  \\
 
 
 c_n= \intop_{ -\infty }^{\infty }  f(x) \Psi^*(x)     dx\\

 c_n=\intop_{ 0 }^{L } \sqrt{\frac{2}{L}}sin(\frac{ \pi x}{L}) \sqrt{\frac{2}{3L}}sin(\frac{n \pi x}{3L})dx \\
 
 c_n=\frac{2}{L\sqrt{3}}\intop_{ 0 }^{L } sin(\frac{ \pi x}{L}) sin(\frac{n \pi x}{3L})dx \\




being \ \frac{ \pi }{3L}=\alpha \\

 c_n=\frac{2}{L\sqrt{3}}\intop_{ 0 }^{L } sin(3\alpha x) sin(n \alpha x)dx \\


 c_1=\frac{1}{L\sqrt{3}}\intop_{ 0 }^{L } 2sin(3\alpha x) sin( 1\alpha x)dx \\
 
 
\ following \ trigonometric \ identity,\\

cos(a)-cos(b)=-2sin(\frac{a+b}{2})sin(\frac{a-b}{2})\\
cos(b)-cos(a)=2sin(\frac{a+b}{2})sin(\frac{a-b}{2}) \\
smaller \ comes \ first \\


     c_1=\frac{1}{L\sqrt{3}}\intop_{ 0 }^{L } [cos(-2\alpha x)-cos(4\alpha x)]dx \\


     c_1=\frac{1}{L\sqrt{3}}[\frac{sin(\frac{ -2\pi }{3L} L)}{\frac{- 2\pi }{3L}} 
    
    
   -\frac{sin(4\frac{ \pi }{3L} L)}{4\frac{ \pi }{3L}}  ]\\  
    \\
   
     
    c_1=\frac{3}{\sqrt{3}}[\frac{sin(\frac{ 2\pi }{3} )}{ 2\pi } 
    
    
   -\frac{sin(4\frac{ \pi }{3} )}{4 \pi }  ]\\  
    \\
    
    analogously, \\

     c_2=\frac{1}{L\sqrt{3}}\intop_{ 0 }^{L } [cos(-1\alpha x)-cos(5\alpha x)]dx \\

       c_2=\frac{1}{\sqrt{3}}[\frac{sin(\frac{ -1\pi }{3} )}{ -1\pi } 
    
    
   -\frac{sin(5\frac{ \pi }{3} )}{5 \pi }  ]\\
   
   
     c_3=\frac{1}{L\sqrt{3}}\intop_{ 0 }^{L } [cos(0\alpha x)-cos(6\alpha x)]dx \\

       c_3=\frac{1}{\sqrt{3}}[1
    
    
   -3\frac{sin(6\frac{ \pi }{3} )}{6 \pi }  ]\\
    
    
     c_4=\frac{1}{L\sqrt{3}}\intop_{ 0 }^{L } [cos(\alpha x)-cos(7\alpha x)]dx \\
    
    c_4=\frac{3}{\sqrt{3}}[\frac{sin(\frac{ \pi }{3} )}{ \pi } 
    
    
   -\frac{sin(7\frac{ \pi }{3} )}{7 \pi }  ]\\  
    \\
     



     c_5=\frac{1}{L\sqrt{3}}\intop_{ 0 }^{L } [cos(2\alpha x)-cos(8\alpha x)]dx \\

     c_5=\frac{3}{\sqrt{3}}[\frac{sin(\frac{ 2\pi }{3} )}{ 2\pi } 
    
    
   -\frac{sin(\frac{ 8\pi }{3} )}{8 \pi }  ]\\  
    \\
    
    
     c_6=\frac{1}{L\sqrt{3}}\intop_{ 0 }^{L } [cos(3\alpha x)-cos(9\alpha x)]dx \\

     c_6=\frac{3}{\sqrt{3}}[\frac{sin(\frac{ 3\pi }{3} )}{ 3\pi } 
    
    
   -\frac{sin(\frac{ 9\pi }{3} )}{9 \pi }  ]\\  
   
   
   
       \\ for \ n \neq 3 \ we \ have \\
    
    
     c_n=\frac{1}{L\sqrt{3}}\intop_{ 0 }^{L } [cos((n-3)\alpha x)-cos((n+3)\alpha x)]dx \\

     c_n=\frac{\sqrt{3}}{\pi}[\frac{sin(\frac{ (n-3)\pi }{3} )}{ (n-3) } 
    
    
   -\frac{sin(\frac{ (n+3)\pi }{3} )}{(n+3)  }  ]\\  
$

<IPython.core.display.Latex object>